# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-12 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20220208_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerita',
            name='stress',
            field=models.IntegerField(blank=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
