# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-12 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_cerita_stress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerita',
            name='stress',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
