# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_auto_20220212_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerita',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cerita',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
