# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-12 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_auto_20220212_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerita',
            name='anonymous',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='cerita',
            name='is_publish',
            field=models.BooleanField(),
        ),
    ]
