# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-13 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_auto_20220212_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gambar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255)),
                ('foto', models.ImageField(null=True, upload_to='cover/')),
            ],
        ),
    ]
