# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-13 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0011_auto_20220213_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='cerita',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cerita',
            name='gambar',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.SET_DEFAULT, to='story.Gambar'),
        ),
    ]
