# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-13 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0013_auto_20220213_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='gambar',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
