# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-13 18:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0014_gambar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255)),
                ('coment', models.TextField()),
                ('anonymous', models.BooleanField()),
                ('gambar', models.ForeignKey(default=25, on_delete=django.db.models.deletion.SET_DEFAULT, to='story.Gambar')),
                ('postingan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='story.Cerita')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
