# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-13 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0015_komentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='publish',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
