# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-13 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0016_komentar_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='coment',
            field=models.TextField(blank=True),
        ),
    ]
