# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-14 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0017_auto_20220214_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='coment',
            field=models.TextField(),
        ),
    ]
