# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-14 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0018_auto_20220214_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cerita',
            name='gambar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='story.Gambar'),
        ),
    ]
